// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if Supabase credentials are properly configured
const isSupabaseConfigured = SUPABASE_URL && 
  SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_URL !== 'https://your-project.supabase.co' && 
  SUPABASE_URL !== 'your_supabase_url' &&
  SUPABASE_PUBLISHABLE_KEY !== 'your-public-anon-key' &&
  SUPABASE_PUBLISHABLE_KEY !== 'your_supabase_anon_key';

// Demo admin credentials
const DEMO_ADMIN = {
  email: 'berkecansuskun1998@gmail.com',
  password: '7892858a'
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});